update_fastlane
fastlane_version "1.111.0"
import_from_git(url: 'git@github.com:AndrewSB/fastlane.git', path: 'Fastfile')

default_platform :ios

platform :ios do
  lane :test do
    scan
  end

  lane :beta do
    begin ensure_git_status_clean    
    rescue => exception
      UI.error("git status was dirty! It was: \n#{`git status`}")
      throw exception
    end

    match_build_number_to_git(project: 'wrytr.xcodeproj', branch: 'master')

    itc(destination: 'TestFlight', project: 'wrytr.xcodeproj', scheme: 'wrytr')
    push_notif(title: 'wrytr deployed to Testflight!')
  end

  lane :release do
    begin ensure_git_status_clean    
    rescue => exception
      UI.error("git status was dirty! It was: \n#{`git status`}")
      throw exception
    end

    match_build_number_to_git(project: 'wrytr.xcodeproj', branch: 'master')
    
    itc(destination: 'App Store', project: 'wrytr.xcodeproj', scheme: 'wrytr')
    push_notif(title: 'wrytr deployed to App Store!')
  end
end
