update_fastlane
fastlane_version "1.111.0"
import_from_git(url: 'git@github.com:AndrewSB/fastlane.git', path: 'Fastfile')

default_platform :ios

platform :ios do
  lane :test do
    scan
  end

  lane :beta do
    match_build_number_to_git(project: 'wrytr.xcodeproj', branch: 'master')
    ensure_git_status_clean    

    itc(destination: 'TestFlight', project: 'wrytr.xcodeproj', scheme: 'wrytr')
    push_notif(title: 'wrytr deployed to Testflight!'
  end

  lane :release do
    match_build_number_to_git(project: 'wrytr.xcodeproj', branch: 'master')
    ensure_git_status_clean    
    
    itc(destination: 'App Store', project: 'wrytr.xcodeproj', scheme: 'wrytr')
    push_notif(title: 'wrytr deployed to App Store!'
  end
end
