update_fastlane
fastlane_version "1.111.0"
import_from_git(url: 'git@github.com:AndrewSB/fastlane.git', path: 'Fastfile')

default_platform :ios

platform :ios do
  lane :test do
    scan
  end

  lane :beta do
    itc(destination: 'TestFlight', project: 'wrytr.xcodeproj', scheme: 'wrytr')
  end

  lane :release do
    itc(destination: 'App Store', project: 'wrytr.xcodeproj', scheme: 'wrytr')
  end
end
